apiVersion: v1
kind: ReplicationController
metadata:
  name: gradientzoo-api-rc
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: gradientzoo-api
  # template defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: gradientzoo-api
    spec:
      containers:
        - name: gradientzoo-api
          image: gcr.io/gradientzoo-1233/gradientzoo-api
          ports:
            - containerPort: 8000