apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gradientzoo-api-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gradientzoo-api
    spec:
      containers:
        - name: gradientzoo-api
          image: gcr.io/gradientzoo-1233/gradientzoo-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRESQL_PORT
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: port
            - name: POSTGRESQL_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: name
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: password
            - name: POSTGRESQL_SSLMODE
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: sslmode
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: bucket
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: region
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: secret
            - name: STRIPE_SECRET_LIVE
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: live
            - name: STRIPE_SECRET_TEST
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: test